### PR TITLE
Setup MongoDB for the project

### PR DESCRIPTION
**Pull request by swarnjit**
fix the minor mistake for the command name to check the installation of MongoDB and revert the changes because of conflict resolution wrong option selection.

### CODE REVIEW

**Review by skassam21 — COMMENTED** [review]
This looks good to me - instructions are clear. I was hoping that we'd also add some code to connect to the mongodb instance on starting of the application, as well as installing Mongoose - and setting up a basic user model - however, this is something that @russ430 can tackle if you coordinate well

**Review by skassam21 — COMMENTED** [review]
Also, I wonder why your change logs look a bit funny - there seems to be more on dev in this PR than what is currently on dev

**Comment by skassam21** [comment]
@swarnjit did you want to close and reopen this PR to see the problem changes again? Let me know once you do so I can give a proper review!

**Comment by swarnjit** [comment]
Some changes didnot make it to the PR

**Pull request closed without merging**
